V rajdeep/dev 12012022
moirf/azure-sdk-for-js pull request #3
Opened 2022-01-12 12:18 UTC by v-rajdeep

2022-01-17 03:17 UTC, moirf requested changes

2022-01-17 03:17 UTC, moirf commented on sdk/communication/communication-calling-server/test/public/callConnection.spec.ts
> +        // this.skip();
do you forget to remove the comment?

2022-01-17 03:17 UTC, moirf commented on sdk/communication/communication-calling-server/test/public/callConnection.spec.ts
> +    it.only("Run hold_resume_audio scenario", async function(this: Context) {
hold_resume not changed to remove/add default audio group?

2022-01-17 03:17 UTC, moirf commented on sdk/communication/communication-calling-server/test/public/callConnection.spec.ts
>          const playAudioOptions: PlayAudioOptions = {
don't put loop true by default, get the variable to set it.

2022-01-17 03:17 UTC, moirf commented on sdk/communication/communication-calling-server/test/public/callConnection.spec.ts
> +        await TestUtils.delayIfLive();
Can you check if rename this to waitForOperationCompletion

2022-01-18 14:04 UTC, v-mausha commented on sdk/communication/communication-calling-server/package.json
>    },
not seeing any new changes, I think no need to check-in this file.

2022-01-19 00:25 UTC, moirf commented on sdk/communication/communication-calling-server/test/public/serverCall.spec.ts
> +        recorder = record(this, environmentSetup);
does this space intentional?

2022-01-19 00:25 UTC, merged